In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [3]:
# download and parse HTML

start_url = "https://en.wikipedia.org/wiki/Tesla,_Inc."

# download the HTML from start_url
downloaded_html = requests.get(start_url)

# parse HTML with BeautifulSoup and create a soup object
soup = BeautifulSoup(downloaded_html.text)

# save a local copy
with open('downloaded.html', 'w', encoding='utf-8') as file:
    file.write(soup.prettify())

In [5]:
# select table.wikitable

full_table = soup.select('table.wikitable')

print(full_table)

[<table class="wikitable">
<tbody><tr style="text-align:center;">
<th>Quarter</th>
<th>Cumulative<br/>production</th>
<th>Total<br/>production</th>
<th>Model S<br/>sales</th>
<th>Model X<br/>sales</th>
<th>Model 3<br/>sales
</th>
<th>Model Y<br/>sales<sup class="reference" id="cite_ref-140"><a href="#cite_note-140">[a]</a></sup></th>
<th>Total<br/>sales<sup class="reference" id="cite_ref-141"><a href="#cite_note-141">[b]</a></sup></th>
<th>In transit<sup class="reference" id="cite_ref-142"><a href="#cite_note-142">[c]</a></sup></th>
<th>Source
</th></tr>
<tr style="text-align:center;">
<td>Q1 2013</td>
<td>N/A</td>
<td>5,000+</td>
<td>4,900</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>4,900</td>
<td></td>
<td><sup class="reference" id="cite_ref-143"><a href="#cite_note-143">[140]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2013</td>
<td>N/A</td>
<td>N/A</td>
<td>5,150</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>5,150</td>
<td></td>
<td><sup class="reference" id="cite_ref-144"><a href="#cite_note-144">[141]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2013</td>
<td>N/A</td>
<td>N/A</td>
<td>5,500+</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>5,500+</td>
<td></td>
<td><sup class="reference" id="cite_ref-145"><a href="#cite_note-145">[142]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2013</td>
<td>~34,851</td>
<td>6,587</td>
<td>6,892</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>6,892</td>
<td></td>
<td><sup class="reference" id="cite_ref-146"><a href="#cite_note-146">[143]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2014</td>
<td>~41,438</td>
<td>7,535</td>
<td>6,457</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>6,457</td>
<td></td>
<td><sup class="reference" id="cite_ref-147"><a href="#cite_note-147">[144]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2014</td>
<td>~48,973</td>
<td>8,763</td>
<td>7,579</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>7,579</td>
<td></td>
<td><sup class="reference" id="cite_ref-148"><a href="#cite_note-148">[145]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2014</td>
<td>~57,736</td>
<td>~7,075</td>
<td>7,785</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>7,785</td>
<td></td>
<td><sup class="reference" id="cite_ref-149"><a href="#cite_note-149">[146]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2014</td>
<td>64,811</td>
<td>11,627</td>
<td>9,834</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>9,834</td>
<td></td>
<td><sup class="reference" id="cite_ref-150"><a href="#cite_note-150">[147]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2015</td>
<td>76,438</td>
<td>11,160</td>
<td>10,045</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>10,045</td>
<td></td>
<td><sup class="reference" id="cite_ref-151"><a href="#cite_note-151">[148]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2015</td>
<td>89,245</td>
<td>12,807</td>
<td>11,532</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>11,532</td>
<td></td>
<td><sup class="reference" id="cite_ref-152"><a href="#cite_note-152">[149]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2015</td>
<td>102,336</td>
<td>13,091</td>
<td>11,597</td>
<td>6</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>11,603</td>
<td></td>
<td><sup class="reference" id="cite_ref-153"><a href="#cite_note-153">[150]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2015</td>
<td>116,373</td>
<td>14,037</td>
<td>17,272</td>
<td>206</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>17,478</td>
<td></td>
<td><sup class="reference" id="cite_ref-154"><a href="#cite_note-154">[151]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2016</td>
<td>131,883</td>
<td>15,510</td>
<td>12,420</td>
<td>2,400</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>14,820</td>
<td>2,615</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2016_155-0"><a href="#cite_note-Tesla1Q2016-155">[152]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2016</td>
<td>150,228</td>
<td>18,345</td>
<td>9,764</td>
<td>4,638</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>14,402</td>
<td>5,150</td>
<td><sup class="reference" id="cite_ref-156"><a href="#cite_note-156">[153]</a></sup><sup class="reference" id="cite_ref-157"><a href="#cite_note-157">[154]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2016</td>
<td>175,413</td>
<td>25,185</td>
<td>16,047</td>
<td>8,774</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>24,821</td>
<td>5,065</td>
<td><sup class="reference" id="cite_ref-158"><a href="#cite_note-158">[155]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2016<sup class="reference" id="cite_ref-159"><a href="#cite_note-159">[d]</a></sup></td>
<td>200,295</td>
<td>24,882</td>
<td>12,700</td>
<td>9,500</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>22,254</td>
<td>6,450</td>
<td><sup class="reference" id="cite_ref-160"><a href="#cite_note-160">[156]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2016final_161-0"><a href="#cite_note-Tesla4Q2016final-161">[157]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2017</td>
<td>225,713</td>
<td>25,418</td>
<td>~13,450</td>
<td>~11,550</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>25,051</td>
<td>~4,650</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2017_162-0"><a href="#cite_note-Tesla1Q2017-162">[158]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2017</td>
<td>251,421</td>
<td>25,708</td>
<td>~12,000</td>
<td>~10,000</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>22,026</td>
<td>~3,500</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2017_163-0"><a href="#cite_note-Tesla2Q2017-163">[159]</a></sup><sup class="reference" id="cite_ref-164"><a href="#cite_note-164">[160]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2017</td>
<td>276,757</td>
<td>25,336</td>
<td>14,065</td>
<td>11,865</td>
<td>222</td>
<td style="background:#f1f5fa;"></td>
<td>26,137</td>
<td>4,820</td>
<td><sup class="reference" id="cite_ref-Tesla3Q2017_165-0"><a href="#cite_note-Tesla3Q2017-165">[161]</a></sup><sup class="reference" id="cite_ref-3Q2017Tesla250K_166-0"><a href="#cite_note-3Q2017Tesla250K-166">[162]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2017</td>
<td>301,322</td>
<td>24,565</td>
<td>~15,200</td>
<td>~13,120</td>
<td>1,542</td>
<td style="background:#f1f5fa;"></td>
<td>29,967</td>
<td>3,380</td>
<td><sup class="reference" id="cite_ref-Tesla4Q2017_167-0"><a href="#cite_note-Tesla4Q2017-167">[163]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2017_AggProduction_168-0"><a href="#cite_note-Tesla4Q2017_AggProduction-168">[164]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2017final_169-0"><a href="#cite_note-Tesla4Q2017final-169">[165]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2018</td>
<td>335,816</td>
<td>34,494</td>
<td>11,730</td>
<td>10,070</td>
<td>8,182</td>
<td style="background:#f1f5fa;"></td>
<td>29,997</td>
<td>6,100</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2018_170-0"><a href="#cite_note-Tesla1Q2018-170">[166]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2018</td>
<td>389,155</td>
<td>53,339</td>
<td>10,930</td>
<td>11,370</td>
<td>18,440</td>
<td style="background:#f1f5fa;"></td>
<td>40,740</td>
<td>15,058</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2018_171-0"><a href="#cite_note-Tesla2Q2018-171">[167]</a></sup><sup class="reference" id="cite_ref-Tesla2Q2018final_172-0"><a href="#cite_note-Tesla2Q2018final-172">[168]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2018</td>
<td>469,297</td>
<td>80,142</td>
<td>14,470</td>
<td>13,190</td>
<td>56,065</td>
<td style="background:#f1f5fa;"></td>
<td>83,725</td>
<td>11,824</td>
<td><sup class="reference" id="cite_ref-Tesla3Q2018_173-0"><a href="#cite_note-Tesla3Q2018-173">[169]</a></sup><sup class="reference" id="cite_ref-Tesla3Q2018final_174-0"><a href="#cite_note-Tesla3Q2018final-174">[170]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2018</td>
<td>555,852</td>
<td>86,555</td>
<td>13,500</td>
<td>14,050</td>
<td>63,359</td>
<td style="background:#f1f5fa;"></td>
<td>90,700</td>
<td>2,907</td>
<td><sup class="reference" id="cite_ref-Tesla4Q2018_175-0"><a href="#cite_note-Tesla4Q2018-175">[171]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2018final_114-1"><a href="#cite_note-Tesla4Q2018final-114">[114]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2019</td>
<td>632,952</td>
<td>77,100</td>
<td colspan="2">12,100</td>
<td>50,900</td>
<td style="background:#f1f5fa;"></td>
<td>63,000</td>
<td>10,600</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2019_176-0"><a href="#cite_note-Tesla1Q2019-176">[172]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2019</td>
<td>720,000</td>
<td>87,048</td>
<td colspan="2">17,650</td>
<td>77,550</td>
<td style="background:#f1f5fa;"></td>
<td>95,200</td>
<td>7,400</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2019_177-0"><a href="#cite_note-Tesla2Q2019-177">[173]</a></sup><sup class="reference" id="cite_ref-wired20190703_178-0"><a href="#cite_note-wired20190703-178">[174]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2019</td>
<td>816,155</td>
<td>96,155</td>
<td colspan="2">17,483</td>
<td>79,703</td>
<td style="background:#f1f5fa;"></td>
<td>97,186</td>
<td></td>
<td><sup class="reference" id="cite_ref-Tesla3Q2019_179-0"><a href="#cite_note-Tesla3Q2019-179">[175]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2019</td>
<td>921,046</td>
<td>104,891</td>
<td colspan="2">19,450</td>
<td>92,550</td>
<td style="background:#f1f5fa;"></td>
<td>112,000</td>
<td></td>
<td><sup class="reference" id="cite_ref-Tesla4Q2019_113-1"><a href="#cite_note-Tesla4Q2019-113">[113]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2020</td>
<td>1,023,718</td>
<td>102,672</td>
<td colspan="2">12,200</td>
<td colspan="2">76,200</td>
<td>88,400</td>
<td></td>
<td><sup class="reference" id="cite_ref-180"><a href="#cite_note-180">[176]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2020</td>
<td>1,105,990</td>
<td>82,272</td>
<td colspan="2">10,600</td>
<td colspan="2">80,050</td>
<td>90,650</td>
<td></td>
<td><sup class="reference" id="cite_ref-181"><a href="#cite_note-181">[177]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2020</td>
<td>1,251,026
</td>
<td>145,036</td>
<td colspan="2">15,200</td>
<td colspan="2">124,100</td>
<td>139,300</td>
<td></td>
<td><sup class="reference" id="cite_ref-182"><a href="#cite_note-182">[178]</a></sup><sup class="reference" id="cite_ref-183"><a href="#cite_note-183">[179]</a></sup>
</td></tr></tbody></table>, <table class="wikitable sortable">
<tbody><tr>
<th>Opened
</th>
<th>Name
</th>
<th>City
</th>
<th>Country
</th>
<th>Employees
</th>
<th>Products
</th>
<th>Notes
</th></tr>
<tr>
<td align="center">2010
</td>
<td align="left"><a class="mw-redirect" href="/wiki/Tesla_Factory" title="Tesla Factory">Tesla Factory</a>
</td>
<td align="center"><a href="/wiki/Fremont,_California" title="Fremont, California">Fremont, California</a>
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="/wiki/United_States" title="United States">United States</a>
</td>
<td align="center">10,000
</td>
<td align="right"><a href="/wiki/Tesla_Model_S" title="Tesla Model S">Tesla Model S</a> <br/> <a href="/wiki/Tesla_Model_3" title="Tesla Model 3">Tesla Model 3</a> <br/> <a href="/wiki/Tesla_Model_X" title="Tesla Model X">Tesla Model X</a> <br/> <a href="/wiki/Tesla_Model_Y" title="Tesla Model Y">Tesla Model Y</a> <br/> <i><a class="mw-redirect" href="/wiki/Tesla_Roadster_(2020)" title="Tesla Roadster (2020)">Tesla Roadster (2020)</a></i>
</td>
<td align="left">Previously a <a href="/wiki/NUMMI" title="NUMMI">NUMMI</a> factory.
</td></tr>
<tr>
<td align="center">2013
</td>
<td align="left"><a href="/wiki/Tesla_facilities_in_Tilburg" title="Tesla facilities in Tilburg">Tesla facilities in Tilburg</a>
</td>
<td align="center"><a href="/wiki/Tilburg" title="Tilburg">Tilburg</a>
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/23px-Flag_of_the_Netherlands.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/35px-Flag_of_the_Netherlands.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/45px-Flag_of_the_Netherlands.svg.png 2x" width="23"/> </span><a href="/wiki/Netherlands" title="Netherlands">Netherlands</a>
</td>
<td align="center">
</td>
<td align="right"><a href="/wiki/Tesla_Model_S" title="Tesla Model S">Tesla Model S</a> <br/> <a href="/wiki/Tesla_Model_X" title="Tesla Model X">Tesla Model X</a>
</td>
<td align="left">Tesla's first factory outside of the United States.  Final EU assembly of major components from US.
</td></tr>
<tr>
<td align="center">2016
</td>
<td align="left"><a href="/wiki/Giga_Nevada" title="Giga Nevada">Giga Nevada</a>
</td>
<td align="center"><a href="/wiki/Storey_County,_Nevada" title="Storey County, Nevada">Storey County</a>, Nevada
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="/wiki/United_States" title="United States">United States</a>
</td>
<td align="center">7,000
</td>
<td align="right"><a class="mw-redirect" href="/wiki/Lithium-ion_batteries" title="Lithium-ion batteries">Lithium-ion batteries</a> <br/> <a href="/wiki/Tesla_Powerwall" title="Tesla Powerwall">Tesla Powerwall</a> <br/> <a class="mw-redirect" href="/wiki/Tesla_Powerpack" title="Tesla Powerpack">Tesla Powerpack</a> <br/> <a href="/wiki/Tesla_Megapack" title="Tesla Megapack">Tesla Megapack</a>
</td>
<td align="left">Also known as Gigafactory 1.
</td></tr>
<tr>
<td align="center">2017
</td>
<td align="left"><a href="/wiki/Giga_New_York" title="Giga New York">Giga New York</a>
</td>
<td align="center"><a href="/wiki/Buffalo,_New_York" title="Buffalo, New York">Buffalo, New York</a>
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="650" data-file-width="1235" decoding="async" height="12" src="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/23px-Flag_of_the_United_States.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/35px-Flag_of_the_United_States.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/a/a4/Flag_of_the_United_States.svg/46px-Flag_of_the_United_States.svg.png 2x" width="23"/> </span><a href="/wiki/United_States" title="United States">United States</a>
</td>
<td align="center">1,500
</td>
<td align="right"><a class="mw-redirect" href="/wiki/Photovoltaic_cells" title="Photovoltaic cells">Photovoltaic cells</a> <br/> <a class="mw-redirect" href="/wiki/Solar_panels" title="Solar panels">Solar panels</a> <br/> <a class="mw-redirect" href="/wiki/Solar_shingles" title="Solar shingles">Solar shingles</a> <br/> Supercharger equipment
</td>
<td align="left">Also known as Gigafactory 2.
</td></tr>
<tr>
<td align="center">2019
</td>
<td align="left"><a href="/wiki/Giga_Shanghai" title="Giga Shanghai">Giga Shanghai</a>
</td>
<td align="center"><a href="/wiki/Shanghai" title="Shanghai">Shanghai</a>
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="900" decoding="async" height="15" src="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/23px-Flag_of_the_People%27s_Republic_of_China.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/35px-Flag_of_the_People%27s_Republic_of_China.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/45px-Flag_of_the_People%27s_Republic_of_China.svg.png 2x" width="23"/> </span><a href="/wiki/China" title="China">China</a>
</td>
<td align="center">2,000<sup class="reference" id="cite_ref-456"><a href="#cite_note-456">[452]</a></sup>
</td>
<td align="right"><a href="/wiki/Tesla_Model_3" title="Tesla Model 3">Tesla Model 3</a> <br/> <i><a href="/wiki/Tesla_Model_Y" title="Tesla Model Y">Tesla Model Y</a></i>
</td>
<td align="left">Also known as Gigafactory 3. Tesla's first Gigafactory outside of the United States.
</td></tr>
<tr>
<td align="center"><i>2021 Future</i>
</td>
<td align="left"><a href="/wiki/Giga_Berlin" title="Giga Berlin">Giga Berlin</a>
</td>
<td align="center"><a href="/wiki/Gr%C3%BCnheide_(Mark)" title="Grünheide (Mark)">Grünheide</a>, <a href="/wiki/Brandenburg" title="Brandenburg">Brandenburg</a>
</td>
<td align="center"><span class="flagicon"><img alt="" class="thumbborder" data-file-height="600" data-file-width="1000" decoding="async" height="14" src="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/23px-Flag_of_Germany.svg.png" srcset="//upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/35px-Flag_of_Germany.svg.png 1.5x, //upload.wikimedia.org/wikipedia/en/thumb/b/ba/Flag_of_Germany.svg/46px-Flag_of_Germany.svg.png 2x" width="23"/> </span><a href="/wiki/Germany" title="Germany">Germany</a>
</td>
<td align="center"><i>10,000 Future</i><sup class="reference" id="cite_ref-457"><a href="#cite_note-457">[453]</a></sup>
</td>
<td align="right"><i><a class="mw-redirect" href="/wiki/Lithium-ion_batteries" title="Lithium-ion batteries">Lithium-ion batteries</a> <br/> <a href="/wiki/Tesla_Model_3" title="Tesla Model 3">Tesla Model 3</a> <br/> <a href="/wiki/Tesla_Model_Y" title="Tesla Model Y">Tesla Model Y</a></i>
</td>
<td align="left">Also known as Gigafactory 4. Tesla's first Gigafactory in <a href="/wiki/Europe" title="Europe">Europe</a>.
</td></tr>
<tr>
<td align="center"><i>2021 Future</i>
</td>

In [6]:
full_table = soup.select('table.wikitable tbody')[0]

print(full_table)

<tbody><tr style="text-align:center;">
<th>Quarter</th>
<th>Cumulative<br/>production</th>
<th>Total<br/>production</th>
<th>Model S<br/>sales</th>
<th>Model X<br/>sales</th>
<th>Model 3<br/>sales
</th>
<th>Model Y<br/>sales<sup class="reference" id="cite_ref-140"><a href="#cite_note-140">[a]</a></sup></th>
<th>Total<br/>sales<sup class="reference" id="cite_ref-141"><a href="#cite_note-141">[b]</a></sup></th>
<th>In transit<sup class="reference" id="cite_ref-142"><a href="#cite_note-142">[c]</a></sup></th>
<th>Source
</th></tr>
<tr style="text-align:center;">
<td>Q1 2013</td>
<td>N/A</td>
<td>5,000+</td>
<td>4,900</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>4,900</td>
<td></td>
<td><sup class="reference" id="cite_ref-143"><a href="#cite_note-143">[140]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2013</td>
<td>N/A</td>
<td>N/A</td>
<td>5,150</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>5,150</td>
<td></td>
<td><sup class="reference" id="cite_ref-144"><a href="#cite_note-144">[141]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2013</td>
<td>N/A</td>
<td>N/A</td>
<td>5,500+</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>5,500+</td>
<td></td>
<td><sup class="reference" id="cite_ref-145"><a href="#cite_note-145">[142]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2013</td>
<td>~34,851</td>
<td>6,587</td>
<td>6,892</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>6,892</td>
<td></td>
<td><sup class="reference" id="cite_ref-146"><a href="#cite_note-146">[143]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2014</td>
<td>~41,438</td>
<td>7,535</td>
<td>6,457</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>6,457</td>
<td></td>
<td><sup class="reference" id="cite_ref-147"><a href="#cite_note-147">[144]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2014</td>
<td>~48,973</td>
<td>8,763</td>
<td>7,579</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>7,579</td>
<td></td>
<td><sup class="reference" id="cite_ref-148"><a href="#cite_note-148">[145]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2014</td>
<td>~57,736</td>
<td>~7,075</td>
<td>7,785</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>7,785</td>
<td></td>
<td><sup class="reference" id="cite_ref-149"><a href="#cite_note-149">[146]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2014</td>
<td>64,811</td>
<td>11,627</td>
<td>9,834</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>9,834</td>
<td></td>
<td><sup class="reference" id="cite_ref-150"><a href="#cite_note-150">[147]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2015</td>
<td>76,438</td>
<td>11,160</td>
<td>10,045</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>10,045</td>
<td></td>
<td><sup class="reference" id="cite_ref-151"><a href="#cite_note-151">[148]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2015</td>
<td>89,245</td>
<td>12,807</td>
<td>11,532</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>11,532</td>
<td></td>
<td><sup class="reference" id="cite_ref-152"><a href="#cite_note-152">[149]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2015</td>
<td>102,336</td>
<td>13,091</td>
<td>11,597</td>
<td>6</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>11,603</td>
<td></td>
<td><sup class="reference" id="cite_ref-153"><a href="#cite_note-153">[150]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2015</td>
<td>116,373</td>
<td>14,037</td>
<td>17,272</td>
<td>206</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>17,478</td>
<td></td>
<td><sup class="reference" id="cite_ref-154"><a href="#cite_note-154">[151]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2016</td>
<td>131,883</td>
<td>15,510</td>
<td>12,420</td>
<td>2,400</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>14,820</td>
<td>2,615</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2016_155-0"><a href="#cite_note-Tesla1Q2016-155">[152]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2016</td>
<td>150,228</td>
<td>18,345</td>
<td>9,764</td>
<td>4,638</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>14,402</td>
<td>5,150</td>
<td><sup class="reference" id="cite_ref-156"><a href="#cite_note-156">[153]</a></sup><sup class="reference" id="cite_ref-157"><a href="#cite_note-157">[154]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2016</td>
<td>175,413</td>
<td>25,185</td>
<td>16,047</td>
<td>8,774</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>24,821</td>
<td>5,065</td>
<td><sup class="reference" id="cite_ref-158"><a href="#cite_note-158">[155]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2016<sup class="reference" id="cite_ref-159"><a href="#cite_note-159">[d]</a></sup></td>
<td>200,295</td>
<td>24,882</td>
<td>12,700</td>
<td>9,500</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>22,254</td>
<td>6,450</td>
<td><sup class="reference" id="cite_ref-160"><a href="#cite_note-160">[156]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2016final_161-0"><a href="#cite_note-Tesla4Q2016final-161">[157]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2017</td>
<td>225,713</td>
<td>25,418</td>
<td>~13,450</td>
<td>~11,550</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>25,051</td>
<td>~4,650</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2017_162-0"><a href="#cite_note-Tesla1Q2017-162">[158]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2017</td>
<td>251,421</td>
<td>25,708</td>
<td>~12,000</td>
<td>~10,000</td>
<td style="background:#f1f5fa;"></td>
<td style="background:#f1f5fa;"></td>
<td>22,026</td>
<td>~3,500</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2017_163-0"><a href="#cite_note-Tesla2Q2017-163">[159]</a></sup><sup class="reference" id="cite_ref-164"><a href="#cite_note-164">[160]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2017</td>
<td>276,757</td>
<td>25,336</td>
<td>14,065</td>
<td>11,865</td>
<td>222</td>
<td style="background:#f1f5fa;"></td>
<td>26,137</td>
<td>4,820</td>
<td><sup class="reference" id="cite_ref-Tesla3Q2017_165-0"><a href="#cite_note-Tesla3Q2017-165">[161]</a></sup><sup class="reference" id="cite_ref-3Q2017Tesla250K_166-0"><a href="#cite_note-3Q2017Tesla250K-166">[162]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2017</td>
<td>301,322</td>
<td>24,565</td>
<td>~15,200</td>
<td>~13,120</td>
<td>1,542</td>
<td style="background:#f1f5fa;"></td>
<td>29,967</td>
<td>3,380</td>
<td><sup class="reference" id="cite_ref-Tesla4Q2017_167-0"><a href="#cite_note-Tesla4Q2017-167">[163]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2017_AggProduction_168-0"><a href="#cite_note-Tesla4Q2017_AggProduction-168">[164]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2017final_169-0"><a href="#cite_note-Tesla4Q2017final-169">[165]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2018</td>
<td>335,816</td>
<td>34,494</td>
<td>11,730</td>
<td>10,070</td>
<td>8,182</td>
<td style="background:#f1f5fa;"></td>
<td>29,997</td>
<td>6,100</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2018_170-0"><a href="#cite_note-Tesla1Q2018-170">[166]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2018</td>
<td>389,155</td>
<td>53,339</td>
<td>10,930</td>
<td>11,370</td>
<td>18,440</td>
<td style="background:#f1f5fa;"></td>
<td>40,740</td>
<td>15,058</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2018_171-0"><a href="#cite_note-Tesla2Q2018-171">[167]</a></sup><sup class="reference" id="cite_ref-Tesla2Q2018final_172-0"><a href="#cite_note-Tesla2Q2018final-172">[168]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2018</td>
<td>469,297</td>
<td>80,142</td>
<td>14,470</td>
<td>13,190</td>
<td>56,065</td>
<td style="background:#f1f5fa;"></td>
<td>83,725</td>
<td>11,824</td>
<td><sup class="reference" id="cite_ref-Tesla3Q2018_173-0"><a href="#cite_note-Tesla3Q2018-173">[169]</a></sup><sup class="reference" id="cite_ref-Tesla3Q2018final_174-0"><a href="#cite_note-Tesla3Q2018final-174">[170]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2018</td>
<td>555,852</td>
<td>86,555</td>
<td>13,500</td>
<td>14,050</td>
<td>63,359</td>
<td style="background:#f1f5fa;"></td>
<td>90,700</td>
<td>2,907</td>
<td><sup class="reference" id="cite_ref-Tesla4Q2018_175-0"><a href="#cite_note-Tesla4Q2018-175">[171]</a></sup><sup class="reference" id="cite_ref-Tesla4Q2018final_114-1"><a href="#cite_note-Tesla4Q2018final-114">[114]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2019</td>
<td>632,952</td>
<td>77,100</td>
<td colspan="2">12,100</td>
<td>50,900</td>
<td style="background:#f1f5fa;"></td>
<td>63,000</td>
<td>10,600</td>
<td><sup class="reference" id="cite_ref-Tesla1Q2019_176-0"><a href="#cite_note-Tesla1Q2019-176">[172]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2019</td>
<td>720,000</td>
<td>87,048</td>
<td colspan="2">17,650</td>
<td>77,550</td>
<td style="background:#f1f5fa;"></td>
<td>95,200</td>
<td>7,400</td>
<td><sup class="reference" id="cite_ref-Tesla2Q2019_177-0"><a href="#cite_note-Tesla2Q2019-177">[173]</a></sup><sup class="reference" id="cite_ref-wired20190703_178-0"><a href="#cite_note-wired20190703-178">[174]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2019</td>
<td>816,155</td>
<td>96,155</td>
<td colspan="2">17,483</td>
<td>79,703</td>
<td style="background:#f1f5fa;"></td>
<td>97,186</td>
<td></td>
<td><sup class="reference" id="cite_ref-Tesla3Q2019_179-0"><a href="#cite_note-Tesla3Q2019-179">[175]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q4 2019</td>
<td>921,046</td>
<td>104,891</td>
<td colspan="2">19,450</td>
<td>92,550</td>
<td style="background:#f1f5fa;"></td>
<td>112,000</td>
<td></td>
<td><sup class="reference" id="cite_ref-Tesla4Q2019_113-1"><a href="#cite_note-Tesla4Q2019-113">[113]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q1 2020</td>
<td>1,023,718</td>
<td>102,672</td>
<td colspan="2">12,200</td>
<td colspan="2">76,200</td>
<td>88,400</td>
<td></td>
<td><sup class="reference" id="cite_ref-180"><a href="#cite_note-180">[176]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q2 2020</td>
<td>1,105,990</td>
<td>82,272</td>
<td colspan="2">10,600</td>
<td colspan="2">80,050</td>
<td>90,650</td>
<td></td>
<td><sup class="reference" id="cite_ref-181"><a href="#cite_note-181">[177]</a></sup>
</td></tr>
<tr style="text-align:center;">
<td>Q3 2020</td>
<td>1,251,026
</td>
<td>145,036</td>
<td colspan="2">15,200</td>
<td colspan="2">124,100</td>
<td>139,300</td>
<td></td>
<td><sup class="reference" id="cite_ref-182"><a href="#cite_note-182">[178]</a></sup><sup class="reference" id="cite_ref-183"><a href="#cite_note-183">[179]</a></sup>
</td></tr></tbody>

In [7]:
# extract table column headings

table_head = full_table.select('tr th')
print(table_head)

[<th>Quarter</th>, <th>Cumulative<br/>production</th>, <th>Total<br/>production</th>, <th>Model S<br/>sales</th>, <th>Model X<br/>sales</th>, <th>Model 3<br/>sales
</th>, <th>Model Y<br/>sales<sup class="reference" id="cite_ref-140"><a href="#cite_note-140">[a]</a></sup></th>, <th>Total<br/>sales<sup class="reference" id="cite_ref-141"><a href="#cite_note-141">[b]</a></sup></th>, <th>In transit<sup class="reference" id="cite_ref-142"><a href="#cite_note-142">[c]</a></sup></th>, <th>Source
</th>]

In [8]:
for element in table_head:
    print(element.text)

Quarter
Cumulativeproduction
Totalproduction
Model Ssales
Model Xsales
Model 3sales

Model Ysales[a]
Totalsales[b]
In transit[c]
Source

In [9]:
# extract table column headings

table_head = full_table.select('tr th')

table_columns = []
for element in table_head:
    column_label = element.get_text(separator=' ', strip=True)
    table_columns.append(column_label)
    print(column_label)
    
print('---------')
print(table_columns)

Quarter
Cumulative production
Total production
Model S sales
Model X sales
Model 3 sales
Model Y sales [a]
Total sales [b]
In transit [c]
Source
---------
['Quarter', 'Cumulative production', 'Total production', 'Model S sales', 'Model X sales', 'Model 3 sales', 'Model Y sales [a]', 'Total sales [b]', 'In transit [c]', 'Source']

In [11]:
# extract table column headings

table_head = full_table.select('tr th')

table_columns = []
for element in table_head:
    column_label = element.get_text(separator=' ', strip=True)
    column_label = column_label.replace(' ', '_')
    table_columns.append(column_label)
    
print('---------')
print(table_columns)

---------
['Quarter', 'Cumulative_production', 'Total_production', 'Model_S_sales', 'Model_X_sales', 'Model_3_sales', 'Model_Y_sales_[a]', 'Total_sales_[b]', 'In_transit_[c]', 'Source']

In [12]:
# extract table column headings

import re
regex = re.compile('_\[\w\]')

table_columns = []
for element in table_head:
    column_label = element.get_text(separator=' ', strip=True)
    column_label = column_label.replace(' ', '_')
    column_label = regex.sub('', column_label)
    table_columns.append(column_label)
    
print(table_columns)

['Quarter', 'Cumulative_production', 'Total_production', 'Model_S_sales', 'Model_X_sales', 'Model_3_sales', 'Model_Y_sales', 'Total_sales', 'In_transit', 'Source']

In [14]:
# extract the table data (rows)

table_rows = full_table.select('tr')
table_data = []

for index, element in enumerate(table_rows):
    if index > 0:
        row_list = []
        values = element.select('td')
        for value in values:
            row_list.append(value.text)
        table_data.append(row_list)
        
print(table_data)

[['Q1 2013', 'N/A', '5,000+', '4,900', '', '', '', '4,900', '', '[140]\n'], ['Q2 2013', 'N/A', 'N/A', '5,150', '', '', '', '5,150', '', '[141]\n'], ['Q3 2013', 'N/A', 'N/A', '5,500+', '', '', '', '5,500+', '', '[142]\n'], ['Q4 2013', '~34,851', '6,587', '6,892', '', '', '', '6,892', '', '[143]\n'], ['Q1 2014', '~41,438', '7,535', '6,457', '', '', '', '6,457', '', '[144]\n'], ['Q2 2014', '~48,973', '8,763', '7,579', '', '', '', '7,579', '', '[145]\n'], ['Q3 2014', '~57,736', '~7,075', '7,785', '', '', '', '7,785', '', '[146]\n'], ['Q4 2014', '64,811', '11,627', '9,834', '', '', '', '9,834', '', '[147]\n'], ['Q1 2015', '76,438', '11,160', '10,045', '', '', '', '10,045', '', '[148]\n'], ['Q2 2015', '89,245', '12,807', '11,532', '', '', '', '11,532', '', '[149]\n'], ['Q3 2015', '102,336', '13,091', '11,597', '6', '', '', '11,603', '', '[150]\n'], ['Q4 2015', '116,373', '14,037', '17,272', '206', '', '', '17,478', '', '[151]\n'], ['Q1 2016', '131,883', '15,510', '12,420', '2,400', '', '', '14,820', '2,615', '[152]\n'], ['Q2 2016', '150,228', '18,345', '9,764', '4,638', '', '', '14,402', '5,150', '[153][154]\n'], ['Q3 2016', '175,413', '25,185', '16,047', '8,774', '', '', '24,821', '5,065', '[155]\n'], ['Q4 2016[d]', '200,295', '24,882', '12,700', '9,500', '', '', '22,254', '6,450', '[156][157]\n'], ['Q1 2017', '225,713', '25,418', '~13,450', '~11,550', '', '', '25,051', '~4,650', '[158]\n'], ['Q2 2017', '251,421', '25,708', '~12,000', '~10,000', '', '', '22,026', '~3,500', '[159][160]\n'], ['Q3 2017', '276,757', '25,336', '14,065', '11,865', '222', '', '26,137', '4,820', '[161][162]\n'], ['Q4 2017', '301,322', '24,565', '~15,200', '~13,120', '1,542', '', '29,967', '3,380', '[163][164][165]\n'], ['Q1 2018', '335,816', '34,494', '11,730', '10,070', '8,182', '', '29,997', '6,100', '[166]\n'], ['Q2 2018', '389,155', '53,339', '10,930', '11,370', '18,440', '', '40,740', '15,058', '[167][168]\n'], ['Q3 2018', '469,297', '80,142', '14,470', '13,190', '56,065', '', '83,725', '11,824', '[169][170]\n'], ['Q4 2018', '555,852', '86,555', '13,500', '14,050', '63,359', '', '90,700', '2,907', '[171][114]\n'], ['Q1 2019', '632,952', '77,100', '12,100', '50,900', '', '63,000', '10,600', '[172]\n'], ['Q2 2019', '720,000', '87,048', '17,650', '77,550', '', '95,200', '7,400', '[173][174]\n'], ['Q3 2019', '816,155', '96,155', '17,483', '79,703', '', '97,186', '', '[175]\n'], ['Q4 2019', '921,046', '104,891', '19,450', '92,550', '', '112,000', '', '[113]\n'], ['Q1 2020', '1,023,718', '102,672', '12,200', '76,200', '88,400', '', '[176]\n'], ['Q2 2020', '1,105,990', '82,272', '10,600', '80,050', '90,650', '', '[177]\n'], ['Q3 2020', '1,251,026\n', '145,036', '15,200', '124,100', '139,300', '', '[178][179]\n']]

In [15]:
# extract the table data (rows)

table_rows = full_table.select('tr')
table_data = []

for index, element in enumerate(table_rows):
    if index > 0:
        row_list = []
        values = element.select('td')
        for value in values:
            row_list.append(value.text.strip())
        table_data.append(row_list)
        
print(table_data)

[['Q1 2013', 'N/A', '5,000+', '4,900', '', '', '', '4,900', '', '[140]'], ['Q2 2013', 'N/A', 'N/A', '5,150', '', '', '', '5,150', '', '[141]'], ['Q3 2013', 'N/A', 'N/A', '5,500+', '', '', '', '5,500+', '', '[142]'], ['Q4 2013', '~34,851', '6,587', '6,892', '', '', '', '6,892', '', '[143]'], ['Q1 2014', '~41,438', '7,535', '6,457', '', '', '', '6,457', '', '[144]'], ['Q2 2014', '~48,973', '8,763', '7,579', '', '', '', '7,579', '', '[145]'], ['Q3 2014', '~57,736', '~7,075', '7,785', '', '', '', '7,785', '', '[146]'], ['Q4 2014', '64,811', '11,627', '9,834', '', '', '', '9,834', '', '[147]'], ['Q1 2015', '76,438', '11,160', '10,045', '', '', '', '10,045', '', '[148]'], ['Q2 2015', '89,245', '12,807', '11,532', '', '', '', '11,532', '', '[149]'], ['Q3 2015', '102,336', '13,091', '11,597', '6', '', '', '11,603', '', '[150]'], ['Q4 2015', '116,373', '14,037', '17,272', '206', '', '', '17,478', '', '[151]'], ['Q1 2016', '131,883', '15,510', '12,420', '2,400', '', '', '14,820', '2,615', '[152]'], ['Q2 2016', '150,228', '18,345', '9,764', '4,638', '', '', '14,402', '5,150', '[153][154]'], ['Q3 2016', '175,413', '25,185', '16,047', '8,774', '', '', '24,821', '5,065', '[155]'], ['Q4 2016[d]', '200,295', '24,882', '12,700', '9,500', '', '', '22,254', '6,450', '[156][157]'], ['Q1 2017', '225,713', '25,418', '~13,450', '~11,550', '', '', '25,051', '~4,650', '[158]'], ['Q2 2017', '251,421', '25,708', '~12,000', '~10,000', '', '', '22,026', '~3,500', '[159][160]'], ['Q3 2017', '276,757', '25,336', '14,065', '11,865', '222', '', '26,137', '4,820', '[161][162]'], ['Q4 2017', '301,322', '24,565', '~15,200', '~13,120', '1,542', '', '29,967', '3,380', '[163][164][165]'], ['Q1 2018', '335,816', '34,494', '11,730', '10,070', '8,182', '', '29,997', '6,100', '[166]'], ['Q2 2018', '389,155', '53,339', '10,930', '11,370', '18,440', '', '40,740', '15,058', '[167][168]'], ['Q3 2018', '469,297', '80,142', '14,470', '13,190', '56,065', '', '83,725', '11,824', '[169][170]'], ['Q4 2018', '555,852', '86,555', '13,500', '14,050', '63,359', '', '90,700', '2,907', '[171][114]'], ['Q1 2019', '632,952', '77,100', '12,100', '50,900', '', '63,000', '10,600', '[172]'], ['Q2 2019', '720,000', '87,048', '17,650', '77,550', '', '95,200', '7,400', '[173][174]'], ['Q3 2019', '816,155', '96,155', '17,483', '79,703', '', '97,186', '', '[175]'], ['Q4 2019', '921,046', '104,891', '19,450', '92,550', '', '112,000', '', '[113]'], ['Q1 2020', '1,023,718', '102,672', '12,200', '76,200', '88,400', '', '[176]'], ['Q2 2020', '1,105,990', '82,272', '10,600', '80,050', '90,650', '', '[177]'], ['Q3 2020', '1,251,026', '145,036', '15,200', '124,100', '139,300', '', '[178][179]']]

In [16]:
df = pd.DataFrame(table_data, columns=table_columns)

df

,Quarter,Cumulative_production,Total_production,Model_S_sales,Model_X_sales,Model_3_sales,Model_Y_sales,Total_sales,In_transit,Source
0,Q1 2013,N/A,"5,000+","4,900",,,,"4,900",,[140]
1,Q2 2013,N/A,N/A,"5,150",,,,"5,150",,[141]
2,Q3 2013,N/A,N/A,"5,500+",,,,"5,500+",,[142]
3,Q4 2013,"~34,851","6,587","6,892",,,,"6,892",,[143]
4,Q1 2014,"~41,438","7,535","6,457",,,,"6,457",,[144]
5,Q2 2014,"~48,973","8,763","7,579",,,,"7,579",,[145]
6,Q3 2014,"~57,736","~7,075","7,785",,,,"7,785",,[146]
7,Q4 2014,"64,811","11,627","9,834",,,,"9,834",,[147]
8,Q1 2015,"76,438","11,160","10,045",,,,"10,045",,[148]
9,Q2 2015,"89,245","12,807","11,532",,,,"11,532",,[149]
10,Q3 2015,"102,336","13,091","11,597",6,,,"11,603",,[150]
11,Q4 2015,"116,373","14,037","17,272",206,,,"17,478",,[151]
12,Q1 2016,"131,883","15,510","12,420","2,400",,,"14,820","2,615",[152]
13,Q2 2016,"150,228","18,345","9,764","4,638",,,"14,402","5,150",[153][154]
14,Q3 2016,"175,413","25,185","16,047","8,774",,,"24,821","5,065",[155]
15,Q4 2016[d],"200,295","24,882","12,700","9,500",,,"22,254","6,450",[156][157]
16,Q1 2017,"225,713","25,418","~13,450","~11,550",,,"25,051","~4,650",[158]
17,Q2 2017,"251,421","25,708","~12,000","~10,000",,,"22,026","~3,500",[159][160]
18,Q3 2017,"276,757","25,336","14,065","11,865",222,,"26,137","4,820",[161][162]
19,Q4 2017,"301,322","24,565","~15,200","~13,120","1,542",,"29,967","3,380",[163][164][165]
20,Q1 2018,"335,816","34,494","11,730","10,070","8,182",,"29,997","6,100",[166]
21,Q2 2018,"389,155","53,339","10,930","11,370","18,440",,"40,740","15,058",[167][168]
22,Q3 2018,"469,297","80,142","14,470","13,190","56,065",,"83,725","11,824",[169][170]
23,Q4 2018,"555,852","86,555","13,500","14,050","63,359",,"90,700","2,907",[171][114]
24,Q1 2019,"632,952","77,100","12,100","50,900",,"63,000","10,600",[172],None
25,Q2 2019,"720,000","87,048","17,650","77,550",,"95,200","7,400",[173][174],None
26,Q3 2019,"816,155","96,155","17,483","79,703",,"97,186",,[175],None
27,Q4 2019,"921,046","104,891","19,450","92,550",,"112,000",,[113],None
28,Q1 2020,"1,023,718","102,672","12,200","76,200","88,400",,[176],None,None
29,Q2 2020,"1,105,990","82,272","10,600","80,050","90,650",,[177],None,None
30,Q3 2020,"1,251,026","145,036","15,200","124,100","139,300",,[178][179],None,None